name: swift-client

targets:
  swift-client:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources: 
      - swift-client
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ardusa.swift-client
        PRODUCT_MODULE_NAME: swift_client
        DEVELOPMENT_TEAM: 6FY4WG44Y2
        MARKETING_VERSION: 4.3.0
        CURRENT_PROJECT_VERSION: 1
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        SWIFT_EMIT_LOC_STRINGS: true
        PRODUCT_NAME: $(TARGET_NAME)
        CODE_SIGN_STYLE: Automatic

  swift-clientTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - swift-clientTests
    dependencies:
      - target: swift-client
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ardusa.swift-clientTests
        DEVELOPMENT_TEAM: 6FY4WG44Y2
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: true
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/swift-client.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/swift-client
        SWIFT_EMIT_LOC_STRINGS: false
        PRODUCT_NAME: $(TARGET_NAME)
        CODE_SIGN_STYLE: Automatic

schemes:
  swift-client:
    build:
      targets:
        swift-client: all
        swift-clientTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - swift-clientTests
    archive:
      config: Release

options:
  bundleIdPrefix: com.ardusa
  createIntermediateGroups: true
  developmentLanguage: en