name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show available simulators
      run: xcrun simctl list devices available
      
    - name: Clean build folder
      run: xcodebuild clean -project MiraAssistant.xcodeproj -scheme MiraAssistant
      
    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -project MiraAssistant.xcodeproj \
          -scheme MiraAssistant \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
      
    - name: Run unit tests
      run: |
        xcodebuild test-without-building \
          -project MiraAssistant.xcodeproj \
          -scheme MiraAssistant \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
      continue-on-error: false
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ~/Library/Logs/DiagnosticReports/
          ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/
        
  build:
    name: Build
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -project MiraAssistant.xcodeproj \
          -scheme MiraAssistant \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Build for iOS Device (if possible)
      run: |
        xcodebuild build \
          -project MiraAssistant.xcodeproj \
          -scheme MiraAssistant \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true
      
  lint:
    name: Swift Lint
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint --config .swiftlint.yml || echo "SwiftLint config not found, using defaults"
        swiftlint lint --reporter github-actions-logging
      continue-on-error: true