name: Mira Swift Client CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

    - name: Install XcodeGen
      run: |
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        xcodegen generate

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Show available simulators
      run: xcrun simctl list devices available

    - name: Find available iOS simulator
      id: find-simulator
      run: |
        # Find the first available iOS simulator (any iPhone)
        SIMULATOR=$(xcrun simctl list devices available | grep -E "\s+iPhone" | head -1 | sed -E 's/.*\s+(iPhone[^(]*).*/\1/' | sed 's/[[:space:]]*$//')
        if [ -z "$SIMULATOR" ]; then
          echo "No iPhone simulators found, trying any iOS device"
          SIMULATOR=$(xcrun simctl list devices available | grep -E "\s+[A-Za-z].*iOS" | head -1 | sed -E 's/.*\s+([^(]*).*/\1/' | sed 's/[[:space:]]*$//')
        fi
        if [ -z "$SIMULATOR" ]; then
          echo "No iOS simulators found at all!"
          exit 1
        fi
        echo "Using simulator: $SIMULATOR"
        echo "simulator=$SIMULATOR" >> $GITHUB_OUTPUT

    - name: Clean build folder
      run: xcodebuild clean -project swift-client.xcodeproj -scheme swift-client

    - name: Build for testing
      run: |
        xcodebuild build \
          -project swift-client.xcodeproj \
          -scheme swift-client \
          -destination "platform=iOS Simulator,name=${{ steps.find-simulator.outputs.simulator }}"

    - name: Archive build outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          ~/Library/Developer/Xcode/DerivedData/*/Build/Products/
        retention-days: 1

  build:
    name: Build
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

    - name: Install XcodeGen
      run: |
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        xcodegen generate

    - name: Find available iOS simulator
      id: find-simulator
      run: |
        # Find the first available iOS simulator (any iPhone)
        SIMULATOR=$(xcrun simctl list devices available | grep -E "\s+iPhone" | head -1 | sed -E 's/.*\s+(iPhone[^(]*).*/\1/' | sed 's/[[:space:]]*$//')
        if [ -z "$SIMULATOR" ]; then
          echo "No iPhone simulators found, trying any iOS device"
          SIMULATOR=$(xcrun simctl list devices available | grep -E "\s+[A-Za-z].*iOS" | head -1 | sed -E 's/.*\s+([^(]*).*/\1/' | sed 's/[[:space:]]*$//')
        fi
        if [ -z "$SIMULATOR" ]; then
          echo "No iOS simulators found at all!"
          exit 1
        fi
        echo "Using simulator: $SIMULATOR"
        echo "simulator=$SIMULATOR" >> $GITHUB_OUTPUT

    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -project swift-client.xcodeproj \
          -scheme swift-client \
          -destination "platform=iOS Simulator,name=${{ steps.find-simulator.outputs.simulator }}" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Build for iOS Device (if possible)
      run: |
        xcodebuild build \
          -project swift-client.xcodeproj \
          -scheme swift-client \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true

  lint:
    name: Swift Lint
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: |
        swiftlint --config .swiftlint.yml || echo "SwiftLint config not found, using defaults"
        swiftlint lint --reporter github-actions-logging
      continue-on-error: true